### ISSUE TITLE
Display xref provenance

### ISSUE THREAD

**Issue by jmcmurry** [TheJacksonLaboratory/hpo-web#9] opened 2018-02-12 18:36 UTC
to be good citizens, these mappings should be attributed.

<img width="278" alt="screen shot 2018-02-12 at 10 35 04 am" src="https://user-images.githubusercontent.com/3658863/36113089-8166a3f4-0fe0-11e8-9909-4df7ea9a6074.png">

**Comment by pnrobinson** [comment] 2019-10-02 16:06
The issue is that in most cases we do not know which curator made these mappings. Many now are automatic and maybe @drseb should be attributed? I do not think that it is worth adding this extra information to the website, which has enough text as it is. If @drseb and @jmcmurry are OK, I would suggest closing.

**Comment by jmcmurry** [comment] 2019-10-03 00:31
True that there should not be too much displayed here on the website; however, if we could link to somewhere where the provenance IS that would be great. If that is not yet available, can we create a ticket in the corresponding place? Is it MONDO? cc: @mellybelly

**Comment by drseb** [comment] 2019-10-03 05:37
Do we have the provenance actually? It is NOT always me. It is not from mondo afaik

**Comment by pnrobinson** [comment] 2019-10-03 10:24
I do not think we recorded the provenance for the XREFs actually. It is not from MONDO. In some cases I added a few, I believe Seb added a whole bunch with scripts, and probably there were others who added some. In any case let's close this, there is too much else that needs to be done!

**Closed by pnrobinson** 2019-10-03 10:24 UTC
Labels: HPO 1.6
